libri: item_libri.o list.o main.o libri.o
	gcc item_libri.o list.o main.o libri.o -o ex.exe
stackArray.o: 
	gcc -c stackArray.c
item_char.o:
	gcc -c item_char.c
list.o:
	gcc -c list.c
main.o:
	gcc -c main.c
item_libri.o:
	gcc -c item_libri.c
libri.o:
	gcc -c libri.c
balance.o:
	gcc -c balance.c
clean:
	rm -f *.out *.o *.exe 
	cls