string: stackArray.o item_char.o list.o main.o balance.o
	gcc stackArray.o item_char.o list.o main.o balance.o -o ex.exe
stackArray.o: 
	gcc -c stackArray.c
item_char.o:
	gcc -c item_char.c
list.o:
	gcc -c list.c
main.o:
	gcc -c main.c
balance.o:
	gcc -c balance.c
clean:
	rm -f *.out *.o *.exe 
	cls