3a: Esercizio_3A.o vettore.o utils.o
	gcc Esercizio_3A.o vettore.o utils.o -o Esercizio_3A.exe

3b: Esercizio_3B.o vettore.o utils.o
	gcc Esercizio_3B.o vettore.o utils.o -o Esercizio_3B.exe

Esercizio_3A.o:
	gcc -c Esercizio_3A.c

Esercizio_3B.o:
	gcc -c Esercizio_3B.c

vettore.o:
	gcc -c vettore.c

utils.o:
	gcc -c utils.c

clean:
	rm -f *.o *.out